### PR TITLE
Make Embed and Webhook::Embed seamless.

### PR DESCRIPTION
**Pull request by GrapeColor**
# Summary

Add a method that can convert Embed to Webhook::Embed.

---

## Added
Added to_postable method to Embed.

### CODE REVIEW

**Comment by z64** [comment]
I don't know how I feel about this feature yet, but if we do accept it, this should be done by implementing `#to_h` - then it will work with `send_embed` automatically.

**Comment by GrapeColor** [comment]
That's true.
I think it's a cool implementation.
Close this PR and create it again.

**Comment by z64** [comment]
You can just modify this PR if you like. Any excess commits can be removed later if we decide to merge it.

**Comment by GrapeColor** [comment]
Removed to_postable method and added to_hash method.
Most of the contents are ported from Webhook::Embed.

**Comment by Daniel-Worrall** [comment]
`to_h`, not `to_hash` please

**Comment by z64** [comment]
Actually, `to_hash` is correct for our current API.

```rb
response = API::Channel.create_message(token, channel, content, tts, embed ? embed.to_hash : nil)
```

https://github.com/discordrb/discordrb/blob/master/lib/discordrb/bot.rb#L371

**Comment by GrapeColor** [comment]
Changed so that values can be set seamlessly at each field level.
As a side effect of this, you can now set values ​​in each field more concisely than before.
```ruby
# before
channel.send_embed do |embed|
  embed.title = 'The Ruby logo'
  embed.image = Discordrb::Webhooks::EmbedImage.new(url: 'https://www.ruby-lang.org/images/header-ruby-logo.png')
end

# after
channel.send_embed do |embed|
  embed.title = 'The Ruby logo'
  embed.image = { url: 'https://www.ruby-lang.org/images/header-ruby-logo.png' }
end
```
I also added the #to_h alias to the #to_hash method.
I'm not sure if this is a good change...

**Comment by GrapeColor** [comment]
It was overengineering to perform type conversion for the setter methods of `Webhook::Embed`.
So I canceled those commits and changed `#to_hash` to `#to_h`.

Either way, you can pass a value like this:
```ruby
bot.message do |event|
  message = event.message
  return if message.embeds.empty?
  _embed = message.embeds[0]

  event.send_embed do |embed|
    embed.title = _embed.title
    embed.description = _embed.description
    embed.url = _embed.url
    embed.timestamp = _embed.timestamp
    embed.color = _embed.color
    embed.footer = _embed.footer
    embed.image = _embed.image
    embed.thumbnail = _embed.thumbnail
    embed.author = _embed.author
    embed.fields = _embed.fields
  end
end
```

**Pull request closed without merging**
